### ISSUE TITLE
Error while importing custom object

### ISSUE THREAD

**Issue by emmanuelfrancis** [ULSashido/ArrowDB_2_Sashido#1]
I have successfully imported users, but when I tried to import a custom object, I am getting following error

`did not go through! => {"code":119,"error":"This user is not allowed to access non-existent class: objCustom"}
`

Could you please help?

**Comment by ULSashido** [comment]
Make sure you either:
- **Create** the ClassName before hand from the Parse Dashboard
<img width="297" alt="Screen Shot 2022-08-20 at 8 48 57 PM" src="https://user-images.githubusercontent.com/80773129/185770839-e6b4d60e-a1af-4b7c-a824-b886f03e5d41.png">

**OR**
- In the Settings **enable** classes to be created _(not advised security wise, however you can do so, and then disable it)_
<img width="500" alt="enable" src="https://user-images.githubusercontent.com/80773129/185770825-1cc5d256-4fc4-48aa-9329-861bccdb9d08.png">

**Comment by emmanuelfrancis** [comment]
Great, thank you.
